version: '3'
services:
  renovate:
    build: .
    container_name: renovate-bot
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - LOG_LEVEL=debug
    volumes:
      - ./config.js:/usr/src/app/config.js 
